<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "f3manager"
 *
 * Auto generated by Extension Builder 2015-03-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FAL Frontend File Manager',
	'description' => 'This extension extends the fal_securedownload extension with a frontend file manager',
	'category' => 'plugin',
	'author' => 'Philipp Seßner',
	'author_email' => 'philipp.sessner@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
    'modify_tables' => 'tx_falsecuredownload_folder',
	'clearCacheOnLoad' => 1,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'fal_securedownload' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);